### ISSUE TITLE
Java doc build error

### ISSUE THREAD

**Issue by roshanbharathdas** [swandroid/swan-sense-studio#11]
Errors in java doc when building the jars for maven repository

**Comment by vlady88** [comment]
Try uncommenting the following code in the build.gradle file from the root of the project:

`subprojects {
    tasks.withType(Javadoc).all { enabled = false }
}`

**Comment by roshanbharathdas** [comment]
Thanks. I guess this is a temporary solution? Or shall I commit the modification?

**Comment by veaceslav** [comment]
This is a workaround.

**Comment by veaceslav** [comment]
Well, I think is a good idea to disable the javadoc for now. I don't know how to fix them. Disable is commited
