### ISSUE TITLE
Failed to unbind to sensor

### ISSUE THREAD

**Issue by veaceslav** [swandroid/swan-sense-studio#7]
The following piece of code is from EvaluationEngineBase:
initialize:

if (!location.equals(Expression.LOCATION_SELF)
                && !location.equals(Expression.LOCATION_INDEPENDENT)) {
            initializeRemote(id, expression, location);
        } else if (expression instanceof LogicExpression) {
            initialize(id + Expression.LEFT_SUFFIX,

stop:
        if (!location.equals(Expression.LOCATION_SELF)
                && !location.equals(Expression.LOCATION_INDEPENDENT)) {
            stopRemote(id, expression);
        }
        if (expression instanceof LogicExpression) {

As you can see, the stop function have no else if, so unbindFromSensor is being called.
Is it the correct core, or the stop function should also have else if?

**Comment by vlady88** [comment]
It was like this from ancient times, so I would suggest to change it only if we find cases when it crashes because of this.

**Comment by veaceslav** [comment]
The missing else makes the function to call unbindFromSensor and since no sensor was added in the fist place, it will just throw some errors in logcat and exit.
